name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup MySQL server
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800
        container port: 3800
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '5.7'
        mysql database: 'cuisinator'
        mysql root password: 'cuisinator'
        mysql user: 'cuisinator'
        mysql password: 'cuisinator'
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('./cuisinator/.env') || copy('./cuisinator/.env.ci', './cuisinator/.env');"
    - name: Install Dependencies
      run: composer install --working-dir ./cuisinator/. -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php ./cuisinator/artisan key:generate
    - name: Create DB and schemas
      run: |
        mkdir -p ./cuisinator/database
        touch ./cuisinator/database/database.sqlite
        php ./cuisinator/artisan migrate
        php ./cuisinator/artisan db:seed
        php ./cuisinator/artisan ui bootstrap --auth
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: cuisinator/vendor/bin/phpunit ./cuisinator/tests/Unit/ExampleTest.php
